<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IEC104.Master.Application\IEC104.Master.Application.csproj" />
    <ProjectReference Include="..\IEC104.Master.Domain\IEC104.Master.Domain.csproj" />
    <ProjectReference Include="..\IEC104.Master.Infrastructure\IEC104.Master.Infrastructure.csproj" />
    <ProjectReference Include="..\IEC104.Master.WinForms\IEC104.Master.WinForms.csproj" />
  </ItemGroup>

</Project>
